[package]
name = "rustorm"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bytes = "1.10.0"
serde = { version = "1.0.218", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
tokio-postgres = "0.7.13"
uuid = "1.15.1"
