version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: demo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raja
      POSTGRES_DB: demo-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 
    driver: local
